image:
  file: .gitpod.Dockerfile
ports:
- port: 8888
- port: 8501

# VS Code extensions to install

vscode:
  extensions:

    - "eamodio.gitlens"
    - "ms-toolsai.jupyter"
    - "github.vscode-pull-request-github"
    - "ms-python.python"
    - "dotjoshjohnson.xml"
#    - "ms-azuretools.vscode-docker"
