image:
  file: .gitpod.Dockerfile

tasks:
  - name: setupconda
  - before: |
      pip install conda-lock
      echo "PATH="/home/gitpod/.local/bin:$PATH"" >> ${HOME}/.bashrc
      source ~/.bashrc
      conda-lock -p linux-64 -f environment.yml
      mamba create --name dbooth-dev --file conda-linux-64.lock 
      conda activate dbooth-dev
      python -m ipykernel install --user --name=dbooth-dev
      alias notebook="jupyter notebook --NotebookApp.allow_origin='*'"
      conda -V && python -V


ports:
- port: 8888
- port: 8501

# VS Code extensions to install

vscode:
  extensions:

    - "eamodio.gitlens"
    - "ms-toolsai.jupyter"
    - "github.vscode-pull-request-github"
    - "ms-python.python"
    - "dotjoshjohnson.xml"
#    - "ms-azuretools.vscode-docker"
