image:
  file: .gitpod.Dockerfile
ports:
- port: 8888
- port: 8501

# VS Code extensions to install

vscode:
  extensions:
    - "gitpod.gitpod-desktop"
    - "eamodio.gitlens"
    - "ms-toolsai.jupyter"
    - "ms-toolsai.jupyter-keymap"
    - "ms-vscode-remote.remote-ssh"
    - "ms-vscode-remote.remote-ssh-edit"
    - "github.vscode-pull-request-github"
    - "ms-python.python"
    - "ms-python.vscode-pylance"
    - "redhat.vscode-yaml"
    - "dotjoshjohnson.xml"
#    - "ms-azuretools.vscode-docker"
